/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
exporterVersion: 2.2.0
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/adamHead.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
        <group position={[0, -0.01, -0.01]} rotation={[-1.57, 0, 0]}>
          <mesh
            geometry={nodes['node_Eye_L_LowerEyelid_-5732'].geometry}
            material={nodes['node_Eye_L_LowerEyelid_-5732'].material}
            rotation={[-0.31, 0, Math.PI]}>
            <mesh
              geometry={nodes['node_Eye_L_EyelidSegment_08_-5828'].geometry}
              material={nodes['node_Eye_L_EyelidSegment_08_-5828'].material}
              rotation={[-0.31, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes['node_Eye_L_EyelidSegment_15_-5830'].geometry}
              material={nodes['node_Eye_L_EyelidSegment_15_-5830'].material}
              rotation={[-0.31, 0, -Math.PI]}
            />
          </mesh>
          <mesh
            geometry={nodes['node_Eye_L_Sclera_-5734'].geometry}
            material={nodes['node_Eye_L_Sclera_-5734'].material}
            rotation={[0, 0.01, 0]}>
            <mesh
              geometry={nodes['node_Eye_L_Lens_-5962'].geometry}
              material={nodes['node_Eye_L_Lens_-5962'].material}
              rotation={[0, 0, Math.PI]}
              scale={1.13}
            />
          </mesh>
          <mesh
            geometry={nodes['node_Eye_L_Side1_-5736'].geometry}
            material={nodes['node_Eye_L_Side1_-5736'].material}
            rotation={[Math.PI, 1.57, 0]}
          />
          <mesh
            geometry={nodes['node_Eye_L_Side2_-5738'].geometry}
            material={nodes['node_Eye_L_Side2_-5738'].material}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes['node_Eye_L_UpperEyelid_-5740'].geometry}
            material={nodes['node_Eye_L_UpperEyelid_-5740'].material}
            rotation={[0.33, 0, 0]}>
            <mesh
              geometry={nodes['node_Eye_L_EyelidSegment_00_-5772'].geometry}
              material={nodes['node_Eye_L_EyelidSegment_00_-5772'].material}
              rotation={[-0.33, 0, 0]}
            />
            <mesh
              geometry={nodes['node_Eye_L_EyelidSegment_07_-5774'].geometry}
              material={nodes['node_Eye_L_EyelidSegment_07_-5774'].material}
              rotation={[-0.33, 0, 0]}
            />
          </mesh>
        </group>
        <group position={[0, -0.01, -0.01]} rotation={[-1.57, 0, 0]}>
          <mesh
            geometry={nodes['node_Eye_R_LowerEyelid_-5722'].geometry}
            material={nodes['node_Eye_R_LowerEyelid_-5722'].material}
            rotation={[-0.31, 0, Math.PI]}>
            <mesh
              geometry={nodes['node_Eye_R_EyelidSegment_08_-5854'].geometry}
              material={nodes['node_Eye_R_EyelidSegment_08_-5854'].material}
              rotation={[-0.31, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes['node_Eye_R_EyelidSegment_15_-5856'].geometry}
              material={nodes['node_Eye_R_EyelidSegment_15_-5856'].material}
              rotation={[-0.31, 0, -Math.PI]}
            />
          </mesh>
          <mesh
            geometry={nodes['node_Eye_R_Sclera_-5724'].geometry}
            material={nodes['node_Eye_R_Sclera_-5724'].material}
            rotation={[0, -0.03, 0]}>
            <mesh
              geometry={nodes['node_Eye_R_Lens_-5942'].geometry}
              material={nodes['node_Eye_R_Lens_-5942'].material}
              rotation={[0, 0, Math.PI]}
              scale={1.13}
            />
          </mesh>
          <mesh
            geometry={nodes['node_Eye_R_Side1_-5726'].geometry}
            material={nodes['node_Eye_R_Side1_-5726'].material}
            rotation={[Math.PI, 1.57, 0]}
          />
          <mesh
            geometry={nodes['node_Eye_R_Side2_-5728'].geometry}
            material={nodes['node_Eye_R_Side2_-5728'].material}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes['node_Eye_R_UpperEyelid_-5730'].geometry}
            material={nodes['node_Eye_R_UpperEyelid_-5730'].material}
            rotation={[0.33, 0, 0]}>
            <mesh
              geometry={nodes['node_Eye_R_EyelidSegment_00_-5890'].geometry}
              material={nodes['node_Eye_R_EyelidSegment_00_-5890'].material}
              rotation={[-0.33, 0, 0]}
            />
            <mesh
              geometry={nodes['node_Eye_R_EyelidSegment_07_-5892'].geometry}
              material={nodes['node_Eye_R_EyelidSegment_07_-5892'].material}
              rotation={[-0.33, 0, 0]}
            />
          </mesh>
        </group>
        <group rotation={[3.04, 1.57, 0]}>
          <mesh
            geometry={nodes.mesh_Adam_BloodyHeadBracket_10374Adam_BloodyHeadBracket.geometry}
            material={nodes.mesh_Adam_BloodyHeadBracket_10374Adam_BloodyHeadBracket.material}
          />
          <mesh
            geometry={nodes.mesh_Adam_BloodyHeadBracket_10374Adam_BloodyHeadBracket_1.geometry}
            material={nodes.mesh_Adam_BloodyHeadBracket_10374Adam_BloodyHeadBracket_1.material}
          />
        </group>
        <mesh
          geometry={nodes['node_Adam_monitor_back_-5608'].geometry}
          material={materials.Adam_monitors}
          rotation={[3.04, 1.57, 0]}
        />
        <mesh
          geometry={nodes['node_cables_-5610'].geometry}
          material={nodes['node_cables_-5610'].material}
          position={[0, 0, 0.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_00_-5612'].geometry}
          material={nodes['node_Eye_L_Blend_00_-5612'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, -2.67]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_01_-5614'].geometry}
          material={nodes['node_Eye_L_Blend_01_-5614'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, -1.62]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_02_-5616'].geometry}
          material={nodes['node_Eye_L_Blend_02_-5616'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, -0.57]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_03_-5618'].geometry}
          material={nodes['node_Eye_L_Blend_03_-5618'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 0.47]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_04_-5620'].geometry}
          material={nodes['node_Eye_L_Blend_04_-5620'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 1.52]}
        />
        <mesh
          geometry={nodes['node_Eye_L_Blend_05_-5622'].geometry}
          material={nodes['node_Eye_L_Blend_05_-5622'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 2.57]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendBase_-5624'].geometry}
          material={nodes['node_Eye_L_BlendBase_-5624'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 3.14]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_00_-5626'].geometry}
          material={nodes['node_Eye_L_BlendScrew_00_-5626'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 3.14]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_01_-5628'].geometry}
          material={nodes['node_Eye_L_BlendScrew_01_-5628'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, -1.05]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_02_-5630'].geometry}
          material={nodes['node_Eye_L_BlendScrew_02_-5630'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, -2.1]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_03_-5632'].geometry}
          material={nodes['node_Eye_L_BlendScrew_03_-5632'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_04_-5634'].geometry}
          material={nodes['node_Eye_L_BlendScrew_04_-5634'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 1.05]}
        />
        <mesh
          geometry={nodes['node_Eye_L_BlendScrew_05_-5636'].geometry}
          material={nodes['node_Eye_L_BlendScrew_05_-5636'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, -0.01, 2.09]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_01_-5638'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_01_-5638'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_02_-5640'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_02_-5640'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_03_-5642'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_03_-5642'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.55, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_04_-5644'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_04_-5644'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.55, -0.01, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_05_-5646'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_05_-5646'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_06_-5648'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_06_-5648'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_09_-5650'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_09_-5650'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_10_-5652'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_10_-5652'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_11_-5654'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_11_-5654'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_12_-5656'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_12_-5656'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_13_-5658'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_13_-5658'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_L_EyelidSegment_14_-5660'].geometry}
          material={nodes['node_Eye_L_EyelidSegment_14_-5660'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_00_-5664'].geometry}
          material={nodes['node_Eye_R_Blend_00_-5664'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -2.67]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_01_-5666'].geometry}
          material={nodes['node_Eye_R_Blend_01_-5666'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -1.62]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_02_-5668'].geometry}
          material={nodes['node_Eye_R_Blend_02_-5668'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -0.57]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_03_-5670'].geometry}
          material={nodes['node_Eye_R_Blend_03_-5670'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 0.48]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_04_-5672'].geometry}
          material={nodes['node_Eye_R_Blend_04_-5672'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 1.52]}
        />
        <mesh
          geometry={nodes['node_Eye_R_Blend_05_-5674'].geometry}
          material={nodes['node_Eye_R_Blend_05_-5674'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 2.57]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendBase_-5676'].geometry}
          material={nodes['node_Eye_R_BlendBase_-5676'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -3.14]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_00_-5678'].geometry}
          material={nodes['node_Eye_R_BlendScrew_00_-5678'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -3.14]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_01_-5680'].geometry}
          material={nodes['node_Eye_R_BlendScrew_01_-5680'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -1.05]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_02_-5682'].geometry}
          material={nodes['node_Eye_R_BlendScrew_02_-5682'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, -2.09]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_03_-5684'].geometry}
          material={nodes['node_Eye_R_BlendScrew_03_-5684'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_04_-5686'].geometry}
          material={nodes['node_Eye_R_BlendScrew_04_-5686'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 1.05]}
        />
        <mesh
          geometry={nodes['node_Eye_R_BlendScrew_05_-5688'].geometry}
          material={nodes['node_Eye_R_BlendScrew_05_-5688'].material}
          position={[0, -0.01, -0.01]}
          rotation={[1.57, 0.03, 2.09]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_01_-5690'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_01_-5690'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_02_-5692'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_02_-5692'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_03_-5694'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_03_-5694'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.56, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_04_-5696'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_04_-5696'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.55, -0.01, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_05_-5698'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_05_-5698'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_06_-5700'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_06_-5700'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.57, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_09_-5702'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_09_-5702'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_10_-5704'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_10_-5704'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_11_-5706'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_11_-5706'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_12_-5708'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_12_-5708'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_13_-5710'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_13_-5710'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <mesh
          geometry={nodes['node_Eye_R_EyelidSegment_14_-5712'].geometry}
          material={nodes['node_Eye_R_EyelidSegment_14_-5712'].material}
          position={[0, -0.01, -0.01]}
          rotation={[-1.74, 0, 0]}
        />
        <group rotation={[3.04, 1.57, 0]}>
          <mesh geometry={nodes.mesh_mesh_Adam_mask_10520mesh_Adam_mask.geometry} material={materials.Adam_mask} />
          <mesh
            geometry={nodes.mesh_mesh_Adam_mask_10520mesh_Adam_mask_1.geometry}
            material={materials.Adam_Mask_metal}
          />
        </group>
        <group position={[0, 0, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.mesh_mesh_Adam_spine_10522mesh_Adam_spine.geometry}
            material={nodes.mesh_mesh_Adam_spine_10522mesh_Adam_spine.material}
          />
          <mesh
            geometry={nodes.mesh_mesh_Adam_spine_10522mesh_Adam_spine_1.geometry}
            material={nodes.mesh_mesh_Adam_spine_10522mesh_Adam_spine_1.material}
          />
        </group>
        <group position={[0, 0, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.mesh_Object001_10524Object001.geometry}
            material={nodes.mesh_Object001_10524Object001.material}
          />
          <mesh
            geometry={nodes.mesh_Object001_10524Object001_1.geometry}
            material={nodes.mesh_Object001_10524Object001_1.material}
          />
          <mesh geometry={nodes.mesh_Object001_10524Object001_2.geometry} material={materials.Adam_Torso_rubber} />
          <mesh
            geometry={nodes.mesh_Object001_10524Object001_3.geometry}
            material={nodes.mesh_Object001_10524Object001_3.material}
          />
          <mesh geometry={nodes.mesh_Object001_10524Object001_4.geometry} material={materials.Adam_head_plastic} />
          <mesh
            geometry={nodes.mesh_Object001_10524Object001_5.geometry}
            material={nodes.mesh_Object001_10524Object001_5.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/adamHead.gltf')
