/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/house.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={3.03}>
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube002_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube002_8.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube002_9.geometry} material={materials['Material.008']} />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={materials['Material.001']}
        position={[0.05, 4.39, -4.98]}
        rotation={[1.56, 0, -3.13]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.009']}
        position={[-2.25, 4.72, -4.83]}
        rotation={[1.57, 1.57, 0]}
      />
    </group>
  )
}

useGLTF.preload('/house.gltf')
